### ISSUE TITLE
USER STORY 5 : User profile Setting

### ISSUE THREAD

**Issue by Shazi-dani** [Shazi-dani/Garage-Management-System#25]
As a user, I want to be able to update my user profile settings so that I can customize my experience. 

- [ ] Task 5.1: Design profile settings page
- [ ] Task 5.2: Implement profile settings logic 
- [ ] Task 5.3: Test profile settings functionality
