### ISSUE TITLE
USER STORY 7: Supplier Management

### ISSUE THREAD

**Issue by Shazi-dani** [Shazi-dani/Garage-Management-System#29]
As a user, I want to be able to create a new supplier so that I can add new suppliers to the system. 

- [ ] Task 7.1: Design supplier creation form
- [ ] Task 7.2: Implement supplier creation logic 
- [ ] Task 7.3: Test supplier creation functionality
