### ISSUE TITLE
USER STORY 8 : Supplier detail page

### ISSUE THREAD

**Issue by Shazi-dani** [Shazi-dani/Garage-Management-System#30]
As a user, I want to be able to read supplier details so that I can view supplier information. 

- [ ] Task 8.1: Design supplier details page
- [ ] Task 8.2: Implement supplier details logic 
- [ ] Task 8.3: Test supplier details functionality
