### ISSUE TITLE
USER STORY 9: update supplier information

### ISSUE THREAD

**Issue by Shazi-dani** [Shazi-dani/Garage-Management-System#31]
As a user, I want to be able to update supplier information so that I can edit existing suppliers. 

- [ ] Task 9.1: Design supplier update form
- [ ] Task 9.2: Implement supplier update logic 
- [ ] Task 9.3: Test supplier update functionality
