### ISSUE TITLE
USER STORY 10 :  able to delete suppliers

### ISSUE THREAD

**Issue by Shazi-dani** [Shazi-dani/Garage-Management-System#32]
As a user, I want to be able to delete suppliers so that I can remove unwanted suppliers. 

- [ ] Task 10.1: Design supplier deletion functionality 
- [ ] Task 10.2: Implement supplier deletion logic
- [ ] Task 10.3: Test supplier deletion functionality
