### ISSUE TITLE
USER STORY 11 : Add new vehicle/product

### ISSUE THREAD

**Issue by Shazi-dani** [Shazi-dani/Garage-Management-System#33]
As a user, I want to be able to create a new vehicle/product so that I can add new vehicles/products to the system. 

- [ ] Task 11.1: Design vehicle/product creation form
- [ ] Task 11.2: Implement vehicle/product creation logic 
- [ ] Task 11.3: Test vehicle/product creation functionality
