### ISSUE TITLE
USER STORY 12: Read Vehicle/Product Details

### ISSUE THREAD

**Issue by Shazi-dani** [Shazi-dani/Garage-Management-System#34]
As a user, I want to be able to read vehicle/product details so that I can view vehicle/product information. 
 

- [ ] Task 12.1: Design vehicle/product details page
- [ ]  Task 12.2: Implement vehicle/product details logic 
- [ ]  Task 12.3: Test vehicle/product details functionality
