### ISSUE TITLE
USER STORY 13: Update Vehicle/Product

### ISSUE THREAD

**Issue by Shazi-dani** [Shazi-dani/Garage-Management-System#35]
As a user, I want to be able to update vehicle/product information so that I can edit existing vehicles/products. 

- [ ]  Task 13.1: Design vehicle/product update form
- [ ]  Task 13.2: Implement vehicle/product update logic 
- [ ]  Task 13.3: Test vehicle/product update functionality
