### ISSUE TITLE
USER STORY 14: Delete vehicles/products

### ISSUE THREAD

**Issue by Shazi-dani** [Shazi-dani/Garage-Management-System#36]
As a user, I want to be able to delete vehicles/products so that I can remove unwanted vehicles/products. 

- [ ]  Task 14.1: Design vehicle/product deletion functionality 
- [ ]  Task 14.2: Implement vehicle/product deletion logic
- [ ]  Task 14.3: Test vehicle/product deletion functionality
